# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- brew install xctool
- cd Example
script:
- xctool -workspace FMResultsMapping.xcworkspace -scheme FMResultsMapping-Example test CODE_SIGNING_REQUIRED=NO -destination name="iPhone 5s" -sdk iphonesimulator
